---
# tasks file for r_cronpull
- name: Ensure retention folder exists
  become: yes
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
  - { path: "{{ pull_pb_path }}", owner: "{{ pull_pb_owner }}", group: "{{ pull_pb_group }}", mode: "{{ pull_pb_mode }}" }
  - { path: "{{ pull_pb_logfile|dirname }}", owner: 'root', group: 'root', mode: '0755' }

- name: Broaden cron'd PATH scope
  become: yes
  lineinfile:
    path: "/etc/cron.d/{{ pull_pb_lock }}"
    owner: 'root'
    group: 'root'
    mode: '0644'
    create: 'yes'
    insertbefore: BOF
    regexp: "^PATH=.*"
    line: "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"


- name: Add to cron
  become: yes
  lineinfile:
    path: "/etc/cron.d/{{ pull_pb_lock }}"
    owner: 'root'
    group: 'root'
    mode: '0644'
    create: 'yes'
    regexp: "^.*--checkout={{ pull_pb_branch }} --url={{ pull_pb_repo }}.*$"
    line: >-
      {{ pull_pb_cron }} {{ pull_pb_owner }} /usr/bin/flock
      -x -w 300 /tmp/{{ pull_pb_lock }}.lock
      /usr/local/bin/ansible-pull -i localhost
      --checkout={{ pull_pb_branch }}
      --url={{ pull_pb_repo }}
      --directory={{ pull_pb_path }}
      --accept-host-key
      --clean
      {% if pull_only_if_changed -%}
      --only-if-changed
      {%- endif %}
      {% if pull_pb_deploykey | default(false) -%}
      --private-key={{ pull_pb_deploykey }}
      {%- endif %}
      {% if pull_pb_yml | default(false) -%}
      {{ pull_pb_yml }}
      {%- endif %}
      >> {{ pull_pb_logfile }}

- name: Add to logrotate
  become: yes
  template:
    src: templates/etc_logrotate.d_cronpull.j2
    dest: "/etc/logrotate.d/{{ pull_pb_name }}"
    owner: 'root'
    group: 'root'
    mode: '0644'
